# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec7c493530e9a6b2b2a2028a5d1b10a5e7df4f9dcefb4a4aebba8381dc9c9da5f32fc4afbdc736711e7bfaf9d07960157418be68b6ee36e779d04be29f0449ca

test:
  secret_key_base: 2af182c5d9bc0e7e092d38280fc9b4e6251ce4170626b402757db1b007354e36d64a01400fe7f7a15d573a4e4de850ee6bd41a6eb05981f498bd271745714a50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
